# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 612bd448316a4ad5b60037aa8e5b025eb9683b7d831d8dbce748a95813fab7f0ce954b6b196cbf305d738098d1a83aa853832a8525c79378e61fb09b321b0317

test:
  secret_key_base: 2a88422044eb906a5ee037b88e6876d97b7779bf89c5bb7ed114cf992ffe242a8feb91ddaeb149aaceca151d9a303438b8e96e6afe74a647cb20ef692fc618ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
